name: Publish Documentation to Pages

on:
  push:
    branches:
      - main
    paths:
      - docs/**
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    container: asciidoctor/docker-asciidoctor:latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v3
      - name: Build artifact
        run: |
          gem install asciidoctor-multipage
          asciidoctor -r asciidoctor-diagram -r asciidoctor-multipage -b multipage_html5 -D './docs/dist' './docs/**/*.adoc'
          tar --dereference --directory './docs/dist' -cvf "$RUNNER_TEMP/artifact.tar" .
      - name: Upload artifact
        uses: actions/upload-artifact@main
        with:
          name: 'github-pages'
          path: ${{ runner.temp }}/artifact.tar
          retention-days: 1

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1